/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects.$projectId.board'
import { Route as ProjectsProjectIdBomRouteImport } from './routes/projects.$projectId.bom'
import { Route as ProjectsProjectIdConnectorsRouteImport } from './routes/projects.$projectId.connectors'
import { Route as ProjectsProjectIdCutListRouteImport } from './routes/projects.$projectId.cut-list'
import { Route as ProjectsProjectIdDiagramRouteImport } from './routes/projects.$projectId.diagram'
import { Route as ProjectsProjectIdLabelsRouteImport } from './routes/projects.$projectId.labels'
import { Route as ProjectsProjectIdMarginsRouteImport } from './routes/projects.$projectId.margins'
import { Route as ProjectsProjectIdProvenanceRouteImport } from './routes/projects.$projectId.provenance'
import { Route as ProjectsProjectIdTestsRouteImport } from './routes/projects.$projectId.tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBomRoute = ProjectsProjectIdBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdConnectorsRoute =
  ProjectsProjectIdConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCutListRoute =
  ProjectsProjectIdCutListRouteImport.update({
    id: '/cut-list',
    path: '/cut-list',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDiagramRoute =
  ProjectsProjectIdDiagramRouteImport.update({
    id: '/diagram',
    path: '/diagram',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdLabelsRoute = ProjectsProjectIdLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdMarginsRoute =
  ProjectsProjectIdMarginsRouteImport.update({
    id: '/margins',
    path: '/margins',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdProvenanceRoute =
  ProjectsProjectIdProvenanceRouteImport.update({
    id: '/provenance',
    path: '/provenance',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTestsRoute = ProjectsProjectIdTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shared': typeof SharedRoute
  '/showcase': typeof ShowcaseRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/connectors': typeof ProjectsProjectIdConnectorsRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/margins': typeof ProjectsProjectIdMarginsRoute
  '/projects/$projectId/provenance': typeof ProjectsProjectIdProvenanceRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shared': typeof SharedRoute
  '/showcase': typeof ShowcaseRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/connectors': typeof ProjectsProjectIdConnectorsRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/margins': typeof ProjectsProjectIdMarginsRoute
  '/projects/$projectId/provenance': typeof ProjectsProjectIdProvenanceRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shared': typeof SharedRoute
  '/showcase': typeof ShowcaseRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/connectors': typeof ProjectsProjectIdConnectorsRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/margins': typeof ProjectsProjectIdMarginsRoute
  '/projects/$projectId/provenance': typeof ProjectsProjectIdProvenanceRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shared'
    | '/showcase'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/connectors'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/margins'
    | '/projects/$projectId/provenance'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shared'
    | '/showcase'
    | '/projects'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/connectors'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/margins'
    | '/projects/$projectId/provenance'
    | '/projects/$projectId/tests'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/shared'
    | '/showcase'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/connectors'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/margins'
    | '/projects/$projectId/provenance'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SharedRoute: typeof SharedRoute
  ShowcaseRoute: typeof ShowcaseRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/bom': {
      id: '/projects/$projectId/bom'
      path: '/bom'
      fullPath: '/projects/$projectId/bom'
      preLoaderRoute: typeof ProjectsProjectIdBomRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/connectors': {
      id: '/projects/$projectId/connectors'
      path: '/connectors'
      fullPath: '/projects/$projectId/connectors'
      preLoaderRoute: typeof ProjectsProjectIdConnectorsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/cut-list': {
      id: '/projects/$projectId/cut-list'
      path: '/cut-list'
      fullPath: '/projects/$projectId/cut-list'
      preLoaderRoute: typeof ProjectsProjectIdCutListRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/diagram': {
      id: '/projects/$projectId/diagram'
      path: '/diagram'
      fullPath: '/projects/$projectId/diagram'
      preLoaderRoute: typeof ProjectsProjectIdDiagramRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/labels': {
      id: '/projects/$projectId/labels'
      path: '/labels'
      fullPath: '/projects/$projectId/labels'
      preLoaderRoute: typeof ProjectsProjectIdLabelsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/margins': {
      id: '/projects/$projectId/margins'
      path: '/margins'
      fullPath: '/projects/$projectId/margins'
      preLoaderRoute: typeof ProjectsProjectIdMarginsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/provenance': {
      id: '/projects/$projectId/provenance'
      path: '/provenance'
      fullPath: '/projects/$projectId/provenance'
      preLoaderRoute: typeof ProjectsProjectIdProvenanceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tests': {
      id: '/projects/$projectId/tests'
      path: '/tests'
      fullPath: '/projects/$projectId/tests'
      preLoaderRoute: typeof ProjectsProjectIdTestsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdBomRoute: typeof ProjectsProjectIdBomRoute
  ProjectsProjectIdConnectorsRoute: typeof ProjectsProjectIdConnectorsRoute
  ProjectsProjectIdCutListRoute: typeof ProjectsProjectIdCutListRoute
  ProjectsProjectIdDiagramRoute: typeof ProjectsProjectIdDiagramRoute
  ProjectsProjectIdLabelsRoute: typeof ProjectsProjectIdLabelsRoute
  ProjectsProjectIdMarginsRoute: typeof ProjectsProjectIdMarginsRoute
  ProjectsProjectIdProvenanceRoute: typeof ProjectsProjectIdProvenanceRoute
  ProjectsProjectIdTestsRoute: typeof ProjectsProjectIdTestsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdBomRoute: ProjectsProjectIdBomRoute,
  ProjectsProjectIdConnectorsRoute: ProjectsProjectIdConnectorsRoute,
  ProjectsProjectIdCutListRoute: ProjectsProjectIdCutListRoute,
  ProjectsProjectIdDiagramRoute: ProjectsProjectIdDiagramRoute,
  ProjectsProjectIdLabelsRoute: ProjectsProjectIdLabelsRoute,
  ProjectsProjectIdMarginsRoute: ProjectsProjectIdMarginsRoute,
  ProjectsProjectIdProvenanceRoute: ProjectsProjectIdProvenanceRoute,
  ProjectsProjectIdTestsRoute: ProjectsProjectIdTestsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SharedRoute: SharedRoute,
  ShowcaseRoute: ShowcaseRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
